import { ColorIdEnum } from '@/providers/ecommerce-management-provider'

export const predefinedThemes = [
  {
    name: 'Verde Pastel',
    description: 'Suave, fresco e natural',
    colors: [
      {
        colorId: ColorIdEnum.PRIMARY_COLOR,
        hex: '#7CBF94',
        rgb: { r: 124, g: 191, b: 148, a: 1 },
        hsv: { h: 141, s: 35, v: 75, a: 1 },
        title: 'Cor principal',
        description: 'Tons suaves de verde para chamadas e botões.',
      },
      {
        colorId: ColorIdEnum.SECONDARY_COLOR,
        hex: '#C3E5C6',
        rgb: { r: 195, g: 229, b: 198, a: 1 },
        hsv: { h: 126, s: 15, v: 90, a: 1 },
        title: 'Cor secundária',
        description: 'Usada na barra de anúncio e elementos de apoio.',
      },
      {
        colorId: ColorIdEnum.TERTIARY_COLOR,
        hex: '#92D27F',
        rgb: { r: 146, g: 210, b: 127, a: 1 },
        hsv: { h: 103, s: 40, v: 82, a: 1 },
        title: 'Cor de destaque',
        description: 'Destaques em promoções e selos.',
      },
      {
        colorId: ColorIdEnum.BACKGROUND_COLOR,
        hex: '#F8FBF9',
        rgb: { r: 248, g: 251, b: 249, a: 1 },
        hsv: { h: 150, s: 1, v: 98, a: 1 },
        title: 'Cor de fundo',
        description: 'Fundo extremamente leve em tom esverdeado.',
      },
      {
        colorId: ColorIdEnum.TEXT_COLOR,
        hex: '#1B3A2F',
        rgb: { r: 27, g: 58, b: 47, a: 1 },
        hsv: { h: 157, s: 53, v: 23, a: 1 },
        title: 'Cor do texto',
        description: 'Verde escuro com ótimo contraste para leitura.',
      },
    ],
  },
  {
    name: 'Azul Pastel',
    description: 'Leve, relaxante e moderno',
    colors: [
      {
        colorId: ColorIdEnum.PRIMARY_COLOR,
        hex: '#6FB0DA',
        rgb: { r: 111, g: 176, b: 218, a: 1 },
        hsv: { h: 205, s: 49, v: 85, a: 1 },
        title: 'Cor principal',
        description: 'Azul claro para botões e links principais.',
      },
      {
        colorId: ColorIdEnum.SECONDARY_COLOR,
        hex: '#C5E1F4',
        rgb: { r: 197, g: 225, b: 244, a: 1 },
        hsv: { h: 204, s: 19, v: 96, a: 1 },
        title: 'Cor secundária',
        description: 'Área de navegação e destaques suaves.',
      },
      {
        colorId: ColorIdEnum.TERTIARY_COLOR,
        hex: '#80C2F2',
        rgb: { r: 128, g: 194, b: 242, a: 1 },
        hsv: { h: 204, s: 47, v: 95, a: 1 },
        title: 'Cor de destaque',
        description: 'Utilizado em badges e etiquetas promocionais.',
      },
      {
        colorId: ColorIdEnum.BACKGROUND_COLOR,
        hex: '#F7FAFC',
        rgb: { r: 247, g: 250, b: 252, a: 1 },
        hsv: { h: 210, s: 2, v: 99, a: 1 },
        title: 'Cor de fundo',
        description: 'Fundo claro quase branco com leve tom azulado.',
      },
      {
        colorId: ColorIdEnum.TEXT_COLOR,
        hex: '#132F4C',
        rgb: { r: 19, g: 47, b: 76, a: 1 },
        hsv: { h: 213, s: 75, v: 30, a: 1 },
        title: 'Cor do texto',
        description: 'Azul profundo para ótimo contraste.',
      },
    ],
  },
  {
    name: 'Laranja Pastel',
    description: 'Quente, amigável e suave',
    colors: [
      {
        colorId: ColorIdEnum.PRIMARY_COLOR,
        hex: '#F9B66E',
        rgb: { r: 249, g: 182, b: 110, a: 1 },
        hsv: { h: 32, s: 56, v: 98, a: 1 },
        title: 'Cor principal',
        description: 'Laranja médio para botões e destaques.',
      },
      {
        colorId: ColorIdEnum.SECONDARY_COLOR,
        hex: '#FFE1B2',
        rgb: { r: 255, g: 225, b: 178, a: 1 },
        hsv: { h: 36, s: 30, v: 100, a: 1 },
        title: 'Cor secundária',
        description: 'Fundo suave para menus e anúncios.',
      },
      {
        colorId: ColorIdEnum.TERTIARY_COLOR,
        hex: '#F8C27A',
        rgb: { r: 248, g: 194, b: 122, a: 1 },
        hsv: { h: 35, s: 51, v: 97, a: 1 },
        title: 'Cor de destaque',
        description: 'Para selos, mensagens e promoções.',
      },
      {
        colorId: ColorIdEnum.BACKGROUND_COLOR,
        hex: '#FFF9F1',
        rgb: { r: 255, g: 249, b: 241, a: 1 },
        hsv: { h: 36, s: 5, v: 100, a: 1 },
        title: 'Cor de fundo',
        description: 'Fundo claro e quente.',
      },
      {
        colorId: ColorIdEnum.TEXT_COLOR,
        hex: '#4B2F1C',
        rgb: { r: 75, g: 47, b: 28, a: 1 },
        hsv: { h: 26, s: 63, v: 29, a: 1 },
        title: 'Cor do texto',
        description: 'Marrom escuro com contraste forte e legível.',
      },
    ],
  },
]
